### ISSUE TITLE
Data Visualization - Cumulative Lab 

### ISSUE THREAD

**Issue by leksea** [learn-co-curriculum/dsc-data-viz-cumulative-lab#2]
## Link to Canvas

https://w-lekse-ds-course-prep-f7b9883982bf4acaa27afecfbcad1480.flatironschool.saturnenterprise.io/notebooks/workspace/flatiron-curriculum/Prep/dsc-data-viz-cumulative-lab/index.ipynb

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```
# Run this cell without changes
response = requests.get('https://www.gutenberg.org/cache/epub/2264/pg2264.txt')
full_text = response.text

# The beginning describes the source/copyright, it isn't the actual text
# of the play until the 16648th character
macbeth = full_text[4863:]

# Print string summary
print("Data type:", type(macbeth))
print()
print("Number of characters:", len(macbeth))
print()
print("First 500 characters:")
print(macbeth[:500])
```

### Concern

The assignment has incorrect numbers and is missing a set of key instructions affecting the end results.

## (Optional) Proposed Solution

Update the starting character index. Mention text formatting character stripping. Update the frequency table count number.   

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello, @leksea.
May you give us the link to the Canvas page so we can decided which member of the team should work on this? (We don't have access to your SaturnCloud link.)
Thank you for raising this issue.

**Comment by leksea** [comment]
https://learning.flatironschool.com/courses/7380/assignments/258607?module_item_id=613200

On Mon, Nov 27, 2023 at 3:16 PM Brendan Patrick Purdy
***@***.***> wrote:
>
> Hello, @leksea.
> May you give us the link to the Canvas page so we can decided which member of the team should work on this? (We don't have access to your SaturnCloud link.)
> Thank you for raising this issue.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
Alexandra Yakovleva

**Comment by bpurdy-ds** [comment]
Thank you. We'll take a look.

**Comment by bpurdy-ds** [comment]
4863 is correct.

**Comment by bpurdy-ds** [comment]
Including `string.whitespace` to verify the [text formatting characters](https://docs.python.org/3/library/string.html) are removed.
